su:
  # Ansible
  - { type: auth, control: '[success=2 default=ignore]', module_path: pam_succeed_if.so, module_arguments: 'use_uid user notingroup ansible' }
  - { type: auth, control: required, module_path: pam_wheel.so, module_arguments: 'use_uid group=ansible'}
  - { type: auth, control: required, module_path: pam_listfile.so, module_arguments: 'item=user sense=allow onerr=fail file=/etc/security/su-ansible-access'}
  # ec2
  - { type: auth, control: '[success=2 default=ignore]', module_path: pam_succeed_if.so, module_arguments: 'use_uid user notingroup ec2-user' }
  - { type: auth, control: required, module_path: pam_wheel.so, module_arguments: 'use_uid group=ec2-user'}
  - { type: auth, control: required, module_path: pam_listfile.so, module_arguments: 'item=user sense=allow onerr=fail file=/etc/security/su-ec2-access'}  
  # prod users
  - { type: auth, control: '[success=2 default=ignore]', module_path: pam_succeed_if.so, module_arguments: 'use_uid user notingroup prod-users' }
  - { type: auth, control: required, module_path: pam_wheel.so, module_arguments: 'use_uid group=prod-users'}           
  - { type: auth, control: required, module_path: pam_listfile.so, module_arguments: 'item=user sense=allow onerr=fail file=/etc/security/su-prod-access'}
  # dev users
  - { type: auth, control: '[success=2 default=ignore]', module_path: pam_succeed_if.so, module_arguments: 'use_uid user notingroup dev-users' }
  - { type: auth, control: required, module_path: pam_wheel.so, module_arguments: 'use_uid group=dev-users'}           
  - { type: auth, control: required, module_path: pam_listfile.so, module_arguments: 'item=user sense=allow onerr=fail file=/etc/security/su-dev-access'}
    # maint users
  - { type: auth, control: '[success=2 default=ignore]', module_path: pam_succeed_if.so, module_arguments: 'use_uid user notingroup maint-users' }
  - { type: auth, control: required, module_path: pam_wheel.so, module_arguments: 'use_uid group=maint-users'}           
  - { type: auth, control: required, module_path: pam_listfile.so, module_arguments: 'item=user sense=allow onerr=fail file=/etc/security/su-maint-access'}  
     
systemauth:
  - { type: session, control: required, module_path: pam_tty_audit.so, module_arguments: 'disable=* enable=root, ansible' }

passwordauth:
  - { type: session, control: required, module_path: pam_tty_audit.so, module_arguments: 'disable=* enable=root, ansible' }
   
securityfiles:
  su-ansible-access: |
    dev-users
  su-ec2-access: |
    ec2-user
  su-prod-access: |
    prod-users
  su-dev-access: |
    dev-users
    prod-users
  su-maint-access: |
    maint-users
    prod-users