---
# file: full_system_configuration.yaml
# Run this play to configure a machine, or group, or all servers in the correct order if it has never been configured before
# plays are imported in the order they should be run
# uncommented means role is configured
- import_playbook: init_0_config_ansible.yaml
- import_playbook: init_1_config_pam.yaml
- import_playbook: init_2_config_users.yaml
- import_playbook: init_3_update_packages.yaml
- import_playbook: init_4_config_auditd.yaml
- import_playbook: init_5_config_firewalld.yaml