- name: Update root user password
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  tags: root
  vars_files:
    - user_vars/user_info/root_user_info.yaml
  roles:
    - config_user

- name: Configure Ansible audit logging
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  vars_files:
    - user_vars/user_info/ansible_user_info.yaml
  roles:
    - config_user_tty_audit    

- name: Configure User in group ec2-user
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  tags: ec2-user
  vars_files:
  - user_vars/user_info/ec2_user_info.yaml
  roles:
    - config_user_group
    - config_user
    - config_sudo
    - config_user_ssh
    - config_user_tty_audit

- name: Configure Users in group prod-users
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  tags: prod-users
  vars_files:
  - user_vars/user_info/prod_users_info.yaml
  roles:
    - config_user_group
    - config_user
    - config_sudo
    - config_user_ssh
    - config_special_user_ssh
    - config_user_tty_audit

- name: Configure Users in group dev-users
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  tags: dev-users
  vars_files:
  - user_vars/user_info/dev_users_info.yaml
  roles:
    - config_user_group
    - config_user
    - config_sudo
    - config_user_ssh
    - config_user_tty_audit

- name: Configure Users in group maint-users
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  tags: maint-users
  vars_files:
  - user_vars/user_info/maint_users_info.yaml
  roles:
    - config_user_group
    - config_user
    - config_sudo
    - config_user_ssh
    - config_special_user_ssh
    - config_user_tty_audit