- name: Configure system to be managed by Ansible
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars_files:
    - user_vars/user_info/ansible_user_info.yaml
  roles:
    - ssh_baseline
    - sudo_baseline
    - config_user_group
    - config_user
    - config_user_ssh