- name: Update root user password
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  vars_files:
    - user_vars/user_passwords/root_user_info.yaml
  roles:
    - config_users

- name: Configure Users in group prod-users
  hosts: all
  remote_user: ansible
  become: true
  become_method: sudo
  tags: prod-users
  vars_files:
  - user_vars/user_passwords/prod_user_info.yaml
  roles:
    - config_user_group
    - config_users
    - config_user_ssh
