- name: Configure single user play
  hosts: all
  remote_user: ansible
  become: true
  become_method: su
  vars_files:
  - user_vars/user_passwords/single_user_info.yaml
  vars:
    - usergroups: ansible  
  roles:
    - init_4_config_users
    - init_6_config_ssh