- name: 'Write sudo group rules to sudoers on visudo validation'
  lineinfile:
    path: '{{ sudoers_location }}'
    state: present
    insertafter: EOF
    line: '{{ item }}'
    validate: /usr/sbin/visudo -cf %s
  with_items: '{{ sudorules }}'