- name: Configure special SSH setup per host
  block:  
    - name: Create identity directory at  {{ identity_location }}
      file:
        path: '{{ identity_location }}'
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy private key to {{ remote_loc }} per special user
      copy:
        src: '{{ key_location }}'
        dest: '{{ remote_loc }}'
        owner: '{{ username }}'
        group: '{{ username }}'
        mode: 0400
      vars:
        remote_loc: '{{ identity_location }}/{{username}}'
        username: '{{ item.value.username }}'
        key_location: '{{ stored_keys }}/{{ groupname }}/{{ item.value.username }}/{{ item.value.username }}'
      with_dict: '{{ users }}'