- name: Required steps to configure machine to be managed by Ansible
  block:
    - name: Create Ansible's group
      group:
        name: '{{ users.ansible.group }}'
        state: present

    - name: Create Ansible user with password and put in group
      user:
        append: true
        comment: '{{ username }} created by ansible'
        groups: '{{ group }}'
        name: '{{ username }}'
        password: '{{ password }}'
        state: present
      vars:
        group: '{{ users.ansible.group }}'
        password: '{{ users.ansible.password }}'
        username: '{{ users.ansible.username }}'

    - name: Add default sshd_config with ansible allowed
      template:
        src:  '{{ ssh_ansible_config }}'
        dest: '{{ sshd_config }}'
        backup: yes
        owner: root
        group: root
        mode: '600'
        validate: '/usr/sbin/sshd -T -f %s'
