- name: Install or update auditd and its plugins
  block:
    - name: Install or update auditd and its plugins
      yum:
        name:
          - audit
          - audispd-plugins
        state: latest
      async: 300
      poll: 0
      register: yum_sleeper

    - name: 'YUM - Check if auditd completed for: {{ inventory_hostname }}'
      async_status:
        jid: "{{ yum_sleeper.ansible_job_id }}"
      register: job_result
      delay: 15
      until: job_result.finished
      retries: 20