- name: Add default sshd_config with ansible allowed
  template:
    src:  '{{ ssh_ansible_config }}'
    dest: '{{ sshd_config }}'
    backup: yes
    owner: root
    group: root
    mode: '600'
    validate: '/usr/sbin/sshd -T -f %s'

  when: ansible_distribution == 'CentOS'